### PR TITLE
JI-5501 Always clear previousState in resetTask,

### PR DESCRIPTION
**Pull request by makmentins**
reset DOM only if loaded

### CODE REVIEW

**Comment by otacke** [comment]
@makmentins Will probably look at this tomorrow. I am not at my desk today.

**Comment by otacke** [comment]
@makmentins What's the goal here? The pull request is not too verbose :-) I assume you're trying to prevent the previous state from being loaded upon refresh if `resetTask()` was called. That may work on H5P.com - it may erase the entry in database if `getCurrentState` returns `undefined` (don't know, can't look into the code), but other H5P integrations will not. Cmp. https://github.com/otacke/h5p-sort-paragraphs/pull/42 and Erik's confirmation at https://github.com/otacke/h5p-sort-paragraphs/pull/42#issuecomment-1735404565 and amendmend for Sort the Paragraphs at https://github.com/otacke/h5p-sort-paragraphs/pull/43

**Comment by makmentins** [comment]
Yep, I we're still making sure that all of the content is completely reset when `resetTask` is called, in this case the extra conditions were necessary to ensure that it works correctly even if DOM is not loaded (when Essay is a part of a compound content type).

I'm not entirely sure returning `undefined` in `getCurrentState` would ever be a problem, but it's a good observation nonetheless, we should keep it consistent across content types, so I pushed a commit for doing that.
Additionally, same as for state, `isAnswered` should probably also always be reset when resetting task, so I've moved it outside of the condition for DOM manipulations

**Comment by otacke** [comment]
That should do the trick! The expected behavior should be clearly documented in https://h5p.org/documentation/developers/contracts#guides-header-5 It currently does not mention states that are stored in the user data table of the H5P integration.

**Comment by otacke** [comment]
Whoops, never merged that in, sorry.

**Pull request merged**
