### PR TITLE
Add Spanish and Mexican Spanish translations

### PR DESCRIPTION
**Pull request by germanvaleroelizondo**

### CODE REVIEW

**Comment by germanvaleroelizondo** [comment]
Would you know how long it takes for these changes in language files to show up for a Moodle user of the H5P plugin ?

**Comment by otacke** [comment]
@germanvaleroelizondo Unfortunately, I don't. The release is solely up to the H5P core team. I know that Essay is supposed to be updated soon, but I don't know an exact date.

**Comment by germanvaleroelizondo** [comment]
Is there a scheduled release of H5P versions that I can look ?

**Comment by otacke** [comment]
@germanvaleroelizondo No. The H5P core team does not have hard release dates. You would have to ask them for an estimate.

The [code of Essay has been reviewed](https://h5ptechnology.atlassian.net/browse/HFP-1879), but there are still some [changes required with the H5P reporting module](https://h5ptechnology.atlassian.net/browse/HFP-2810).

**Comment by germanvaleroelizondo** [comment]
Thanks. I have done so.

**Pull request merged**
